### ISSUE TITLE
Webpage stuck on Loading after logging in with Spotify.

### ISSUE THREAD

**Issue by ChristianVaughn** [huangdarren1106/huangdarren1106.github.io#3]
After logging in with Spotify the page is stuck on loading and no data is actually loaded. I attached a screenshot of the dev console it that helps debug the issue

![image](https://user-images.githubusercontent.com/4643028/171942483-9395bc0c-a92d-4cb4-ac02-8e854fab2cbf.png)

**Comment by locomoco28** [comment]
You most likely have an addon that blocks the requests, in my case I had PrivacyBadger which was blocking all scripts from `api.discord.com`. I set it to only block cookies and it works afterwards 👍 

![image](https://user-images.githubusercontent.com/32169493/173187385-95d64ac2-a98c-49e3-9910-32be2bb1b8f1.png)

**Comment by ChristianVaughn** [comment]
It just randomly started working after doing nothing so I will close this issue.
